routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'tasks', 'as' => 'task.', 'middleware' => ['auth']], function(){
    Route::any('/list', [
        'as'=>'list',
        'uses'=>'TaskController@showList'
    ]);
    Route::get('create', [
        'as'=>'show.create',
        'uses'=>'TaskController@showCreate'
    ]);
    Route::post('create', [
        'as'=>'store',
        'uses'=>'TaskController@store'
    ]);
    Route::get('{task}', [
        'as'=>'show.update',
        'uses'=>'TaskController@showEdit'
    ]);
    Route::get('{task}/delete', [
        'as'=>'delete',
        'uses'=>'TaskController@delete'
    ]);    
    Route::post('{task}', [
        'as'=>'update',
        'uses'=>'TaskController@update'
    ]);    
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $primaryKey = 'id_task';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'description', 'finished', 'attachment', 'id_user'
    ];

    public function user() 
    {
        return $this->belongsTo(User::class, 'id_user');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect(route('task.list'));
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Storage;
use File;
use Cookie;
use App\Task;
use App\User;

class TaskController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show task list page.
     *
     * @return \Illuminate\Http\Response
     */
    public function showList(Request $request)
    {
        $data = $request->validate([
            'search' => 'min:0|max:255|nullable|regex:/(^[A-Za-z0-9 ]+$)+/',
        ]);

        $hide_finished_tasks = $request->cookie('hide_finished_tasks');

        if ($hide_finished_tasks === 'true') {
            $tasks = Task::where('finished', 0);
        } else {
            $tasks = Task::orderBy('finished', 'asc');
        }

        if ($request->has('search')) {
            $tasks
                ->where('title', 'LIKE', '%' . $request->search . '%')
                ->orWhere('description', 'LIKE', '%' . $request->search . '%');
        }

        return view('pages.task.list', [
            'tasks' => $tasks->orderBy('updated_at', 'desc')->paginate(5), 
            'search' => $request->has('search') ? $request->search : '', 
            'hide_finished_tasks' => $hide_finished_tasks
        ]);
    }

    /**
     * Show the task create page.
     *
     * @return \Illuminate\Http\Response
     */
    public function showCreate()
    {
        return view('pages.task.create', [
            'users' => User::all()
        ]);
    }

    /**
     * Store a new task.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => 'required|max:255',
            'description' => 'min:0',
            'attachment' => 'file|mimes:pdf,xml,jpg,jpeg|max:5000',
            'user' => 'integer|nullable|min:1'
        ]);

        $file = $request->file('attachment');
        $path = storage_path('app/public/tasks/attachments/');

        if(!File::exists($path)) {
            File::makeDirectory($path, $mode = 0777, true, true);
        }
        
        if ($file){
            $request->file('attachment')->move($path, $file->getClientOriginalName());
        }

        $task = Task::create([
            'title'                 => $data['title'],
            'description'           => (isset($data['description'])) ? $data['description'] : null,
            'attachment'            => ($file) ? $file->getClientOriginalName() : null,
            'id_user'               => (isset($data['user'])) ? $data['user'] : null,
        ]);

        return redirect(route('task.show.update',[
            'task' => $task->id_task
        ]));
    }    

    /**
     * Show the task edit page.
     *
     * @return \Illuminate\Http\Response
     */
    public function showEdit(Task $task)
    {
        return view('pages.task.edit', [
            'users' => User::all(),
            'task' => $task
        ]);
    } 

    /**
     * Update a task.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $data = $request->validate([
            'title' => 'required|max:255',
            'description' => 'min:0',
            'attachment' => 'file|mimes:pdf,xml,jpg,jpeg|max:5000',
            'user' => 'nullable|integer|min:1',
            'finished' => 'required|boolean',
        ]);

        $file = $request->file('attachment');
        if ($file){
            $file->move('tasks/attachments/',$file->getClientOriginalName());
        }

        $task->title = $data['title'];
        $task->description = $data['description'];
        $task->attachment = ($file) ? $file->getClientOriginalName() : $task->attachment;
        $task->id_user = ($data['user'] !== '') ? $data['user'] : null;
        $task->finished = $data['finished'];
        $task->update();

        return redirect(route('task.show.update', [
            'task' => $task->id_task
        ]));
    }

    /**
     * Delete a task.
     *
     * @return \Illuminate\Http\Response
     */
    public function delete(Task $task)
    {        
        $task->delete();

        return redirect(route('task.list'));
    }             
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Todo application') }}</title>

    <link href="{{ mix('/css/front.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('task.show.create') }}">+ Create a new Task</a></li>
                                    <li><a href="{{ route('task.list') }}">Tasks</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/pages/task/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create Task</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('task.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">Title*</label>

                            <div class="col-md-6">
                                <input id="title" type="title" class="form-control" placeholder="Title" name="title" value="{{ old('title') }}" autofocus>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Description</label>

                            <div class="col-md-6">
                                <textarea id="description" type="title" class="form-control" placeholder="Description" name="description">{{ old('description') }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                        

                        <div class="form-group{{ $errors->has('attachment') ? ' has-error' : '' }}">
                            <label for="attachment" class="col-md-4 control-label">Attachment</label>

                            <div class="col-md-6">
                                <input type="file" id="attachment"  name="attachment" accept="*/*">

                                @if ($errors->has('attachment'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('attachment') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user') ? ' has-error' : '' }}">
                            <label for="user" class="col-md-4 control-label">Assignee</label>

                            <div class="col-md-6">
                                <select name="user" class="form-control">                                    
                                    <option value="">Please select a user</option>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}" @if(old('user') === (string)$user->id) selected @endif>{{ $user->name }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('user'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <a href="{{ route('task.list') }}" class="btn btn-default">Cancel</a>
                                <button type="submit" class="btn btn-primary">
                                    Create
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/task/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Task</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('task.update',['task' => $task->id_task]) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">Title*</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" placeholder="Title" name="title" value="{{ old('title') ? old('title') : $task->title }}" autofocus>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Description</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control" placeholder="Description" name="description">{{ old('description') ? old('description') : $task->description }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                        

                        <div class="form-group{{ $errors->has('attachment') ? ' has-error' : '' }}">
                            <label for="attachment" class="col-md-4 control-label">Attachment</label>

                            <div class="col-md-6">
                                <a href="{{ asset('storage/tasks/attachments/'.$task->attachment) }}" target="blank">{{ $task->attachment }}</a>
                                <input type="file" id="attachment"  name="attachment" accept="*/*">

                                @if ($errors->has('attachment'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('attachment') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user') ? ' has-error' : '' }}">
                            <label for="user" class="col-md-4 control-label">Assignee</label>

                            <div class="col-md-6">
                                <select name="user" class="form-control">                                    
                                    <option value="">Please select a user</option>
                                    @foreach($users as $user)
                                        <option 
                                            value="{{ $user->id }}" 
                                            @if(old('user') && old('user') === (string)$user->id || $task->id_user === $user->id)
                                                selected
                                            @endif
                                        >
                                            {{ $user->name }}
                                        </option>
                                    @endforeach
                                </select>

                                @if ($errors->has('user'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('finished') ? ' has-error' : '' }}">
                            <label for="finished" class="col-md-4 control-label">Status</label>

                            <div class="col-md-6">
                                <select name="finished" class="form-control">                                    
                                    <option value="0" @if(old('finished') === '0' || $task->finished === 0) selected @endif>In progress</option>
                                    <option value="1" @if(old('finished') === '1' || $task->finished === 1) selected @endif>Finished</option>
                                </select>

                                @if ($errors->has('finished'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('finished') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <a href="{{ route('task.list') }}" class="btn btn-default">Cancel</a>
                                <a href="{{ route('task.delete',['task' => $task->id_task]) }}" class="btn btn-danger">Delete</a>
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/task/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Tasks</div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('task.list') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('search') ? ' has-error' : '' }}">
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="search" value="@if(old('search')){{ old('search') }}@else{{ $search }}@endif" placeholder="Search"/>
                                @if ($errors->has('search'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('search') }}</strong>
                                    </span>
                                @endif                                
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary pull-right">
                                    Search
                                </button>
                            </div>       
                        </div>
                    </form>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="pull-left">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" id="hide-finished-tasks" @if($hide_finished_tasks === 'true') checked="" @endif name="hide_finished_tasks" onchange="hideFinishedTasks(this)">Hide finished tasks
                                    </label>
                                </div>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('task.show.create') }}" class="btn btn-primary pull-right">+ Create a new Task</a>
                            </div>
                        </div>
                    </div>                    
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Created</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                        <tr>
                            <th scope="row">{{ $task->id_task }}</th>
                            <td>{{ $task->title }}</th>
                            <td>{{ $task->description }}</th>
                            <td>{{ $task->created_at->diffForHumans(null,false,true,2) }}</th>
                            <td>{{ $task->finished ? 'Finished' : 'In progress' }}</th>
                            <td><a href="{{ route('task.show.update',['task' => $task->id_task]) }}">View</a></th>
                        </tr>
                        @endforeach                                                                                               
                    </tbody>
                </table>
                <div class="col-md-12">
                    <div class="pull-right">
                        {{ $tasks->links() }}
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function hideFinishedTasks(e) {
        var d = new Date();
        d.setTime(d.getTime() + (30*24*60*60*1000));        
        document.cookie = "hide_finished_tasks=" + e.checked + "; expires=" + d.toUTCString() + "; path=/";
        window.location.href = "/tasks/list";
    }
</script>
@endsection